name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.4.0
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
